triggers:
  - cron:
      spec: "* x * * *"
      entryPoint: default
  - foo:
      version: 2
      conditions:
        x: "foo"
      entryPoint: default

flows:
  default:
    - log: "Hello, ${event}!"